name: zip builder

on:
  push:
    branches:
      - master
      - main
  repository_dispatch:
    types: [make_zip]
  workflow_dispatch:
    inputs:
      tag:
        default: "latest"
        description: "Release tag"
        required: true

jobs:
  make-zip:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: "performance_email_notification.zip"
      DEFAULT_TAG: "latest"
    steps:
    - uses: actions/checkout@v3
    - name: remove unwanted folders
      run: rm -rf ./package ./tests
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: setting up docker builder
      run: pip install -r requirements.txt -t ./ --no-cache-dir --compile
    - name: zipping
      run: zip -r -9 $ARTIFACT_NAME .
#    - name: Create artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: task_zip
#        path: ./${{env.ARTIFACT_NAME}}
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: ./${{ env.ARTIFACT_NAME }}
        makeLatest: true
        allowUpdates: true
        tag: ${{ github.event.inputs.tag || env.DEFAULT_TAG }}
